name: Zip Browser Extension

on:
  push:
    branches:
      - main

jobs:
  zip-extension:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create zip file
      run: |
        zip -r extension.zip * -x "*.git*" -x "*.github"
    
    - name: Upload zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: extension.zip
